
name: "Compile and publish pdf"

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update reps
        run: apt update && apt upgrade
      - name: Install deps
        run: apt install texlive-latex-extra make
      - name: Rename output file
        run: mv notes.pdf notes.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: notes.pdf
